#!/usr/bin/env python3
"""Compare the frozen collector labels with the single-reviewer manual audit."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"


def divide(numerator: int, denominator: int) -> float:
    return numerator / denominator if denominator else float("nan")


def main() -> int:
    with (DATA / "argocd_audit_sample.csv").open(newline="", encoding="utf-8") as handle:
        automatic = {int(row["number"]): int(row["collector_external_issue_reference"]) for row in csv.DictReader(handle)}
    with (DATA / "argocd_audit_coding.csv").open(newline="", encoding="utf-8") as handle:
        manual = {int(row["number"]): int(row["manual_external_issue_reference"]) for row in csv.DictReader(handle)}
    if automatic.keys() != manual.keys():
        raise SystemExit("manual-audit keys do not match the frozen audit sample")

    tp = sum(automatic[number] == 1 and manual[number] == 1 for number in manual)
    tn = sum(automatic[number] == 0 and manual[number] == 0 for number in manual)
    fp = sum(automatic[number] == 1 and manual[number] == 0 for number in manual)
    fn = sum(automatic[number] == 0 and manual[number] == 1 for number in manual)
    metrics = [
        ("sample_size", len(manual)),
        ("true_positive", tp),
        ("true_negative", tn),
        ("false_positive", fp),
        ("false_negative", fn),
        ("precision", f"{divide(tp, tp + fp):.3f}"),
        ("recall", f"{divide(tp, tp + fn):.3f}"),
        ("agreement", f"{divide(tp + tn, len(manual)):.3f}"),
    ]
    with (DATA / "argocd_validation.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(["metric", "value"])
        writer.writerows(metrics)
    macros = f"""%% Generated by empirical/validate_manual_audit.py
\\newcommand{{\\ArgoAuditN}}{{{len(manual)}}}
\\newcommand{{\\ArgoAuditTP}}{{{tp}}}
\\newcommand{{\\ArgoAuditTN}}{{{tn}}}
\\newcommand{{\\ArgoAuditFP}}{{{fp}}}
\\newcommand{{\\ArgoAuditFN}}{{{fn}}}
\\newcommand{{\\ArgoAuditPrecision}}{{{divide(tp, tp + fp):.3f}}}
\\newcommand{{\\ArgoAuditRecall}}{{{divide(tp, tp + fn):.3f}}}
\\newcommand{{\\ArgoAuditAgreement}}{{{divide(tp + tn, len(manual)):.3f}}}
"""
    (ROOT / "argocd_validation_macros.tex").write_text(macros, encoding="ascii")
    print(f"PASS: manual audit n={len(manual)}, TP={tp}, TN={tn}, FP={fp}, FN={fn}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
